//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvolveItems
    {
        public int Id { get; set; }
        public int PokedexID { get; set; }
        public int ItemID { get; set; }
        public Nullable<bool> OnTrade { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Pokedex Pokedex { get; set; }
    }
}
