//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokedex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokedex()
        {
            this.AbilityPool = new HashSet<AbilityPool>();
            this.AllowedMoves = new HashSet<AllowedMoves>();
            this.EvolveItems = new HashSet<EvolveItems>();
            this.Pokemon = new HashSet<Pokemon>();
        }
    
        public int Id { get; set; }
        public string PokemonDescription { get; set; }
        public decimal PokemonWeight { get; set; }
        public int ExpMax { get; set; }
        public int CaptureRate { get; set; }
        public string PokemonName { get; set; }
        public Nullable<int> Type1 { get; set; }
        public Nullable<int> Type2 { get; set; }
        public Nullable<int> EvolveThreshold { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbilityPool> AbilityPool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllowedMoves> AllowedMoves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvolveItems> EvolveItems { get; set; }
        public virtual Types Types { get; set; }
        public virtual Types Types1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pokemon> Pokemon { get; set; }
    }
}
