//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemon()
        {
            this.LearnedMoves = new HashSet<LearnedMoves>();
            this.PokemonGroup = new HashSet<PokemonGroup>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PokedexID { get; set; }
        public Nullable<int> PokemonLevel { get; set; }
        public Nullable<int> PokemonExp { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> TrainerID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> AbilityID { get; set; }
        public Nullable<int> StatPoolID { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Nickname { get; set; }
        public bool Shiny { get; set; }
        public bool PokeRus { get; set; }

        public int currentHp;
    
        public virtual Ability Ability { get; set; }
        public virtual Items Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LearnedMoves> LearnedMoves { get; set; }
        public virtual Pokedex Pokedex { get; set; }
        public virtual StatPool StatPool { get; set; }
        public virtual StatusEffects StatusEffects { get; set; }
        public virtual Trainer Trainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PokemonGroup> PokemonGroup { get; set; }

        public string ReturnHP()
        {
            currentHp = StatPool.CurrentHealth(this);

            return currentHp + "\t/ " + StatPool.CurrentHealth(this);

        }
    }
}
