//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_r0739290Entities : DbContext
    {
        public DB_r0739290Entities()
            : base("name=DB_r0739290Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ability> Ability { get; set; }
        public virtual DbSet<AbilityPool> AbilityPool { get; set; }
        public virtual DbSet<AllowedMoves> AllowedMoves { get; set; }
        public virtual DbSet<EffectBundle> EffectBundle { get; set; }
        public virtual DbSet<EvolveItems> EvolveItems { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<LearnedMoves> LearnedMoves { get; set; }
        public virtual DbSet<PlayerInventory> PlayerInventory { get; set; }
        public virtual DbSet<Pokedex> Pokedex { get; set; }
        public virtual DbSet<Pokemon> Pokemon { get; set; }
        public virtual DbSet<PokemonGroup> PokemonGroup { get; set; }
        public virtual DbSet<PokemonMoves> PokemonMoves { get; set; }
        public virtual DbSet<StatCollection> StatCollection { get; set; }
        public virtual DbSet<StatPool> StatPool { get; set; }
        public virtual DbSet<StatusEffects> StatusEffects { get; set; }
        public virtual DbSet<Trainer> Trainer { get; set; }
        public virtual DbSet<Types> Types { get; set; }
        public virtual DbSet<UseCase> UseCase { get; set; }
    }
}
